---
- name: Hello Ansible - quick start
  hosts: localhost
  connection: local
  remote_user: ec2-user
  sudo: yes

  tasks:
    - name: Hello touch_file
      shell: echo {{ ansible_env.FACTER_foo }} >> /tmp/{{ ansible_env.FACTER_bar }}
    - name: Hello echo
      shell: echo "The file /tmp/{{ ansible_env.FACTER_bar }} contains {{ ansible_env.FACTER_foo }}" >> {{ ansible_env.FACTER_heat_outputs_path }}.result
